# Generated by Django 3.0 on 2023-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gujrati_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='Uploaded_Data')),
            ],
        ),
    ]
