# Generated by Django 4.0 on 2023-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gujrati_files',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
